Create Schema
Ghaith-Chrit/SOEN-363 pull request #1
Opened 2023-02-04 01:49 UTC by Chr728

2023-02-04 02:12 UTC, Ghaith-Chrit requested changes

2023-02-04 02:12 UTC, Ghaith-Chrit commented on Schema
> +);
A few points here:
- we can't say hashtag_count and tweet_id at the same time. For example, assume we have two tweets that have the same tweet, so the hashtag_count will be 2 but which tweet_id will you save? Which one do you want to keep? I would suggest removing the tweet_id since there is the "Contains" table that includes that info.
- what is hashtag_name? Why is it capped to varchar(15) only?
- what is the difference between frequency and hashtag_count?
- why is frequency float anyway as well?

2023-02-04 02:12 UTC, Ghaith-Chrit commented on Schema
> +TWEETERid SERIAL NOT NULL,
TWEETERid? Do you mean tweet_id? 
And please stick to one naming convention (better if you choose a known one. You can find anyone you like). This applies to everything you name (e.g., table names, columns, etc.)

2023-02-04 02:12 UTC, Ghaith-Chrit commented on Schema
> +TWEETER_id SERIAL NOT NULL,
same as above

2023-02-04 02:12 UTC, Ghaith-Chrit commented on Schema
> +smodel_name VARCHAR(15) NOT NULL,
why is it capped at varchar(15)?

2023-02-04 02:38 UTC, Chr728 commented on Schema
> +lastname VARCHAR(30) NOT NULL
@Ghaith-Chrit its just I thought that every use when they register they will be asked to write a first and famil name for identification purposed and for purposed and for distinguishing between two users who has the same name. that's is why i put family name

2023-02-04 02:40 UTC, Chr728 commented on Schema
> +views_number int,
@Ghaith-Chrit tony decided to put the numbers of people who viewed a specific tweet. so its the total number of people who viewed a specific one tweet, do you still want me to remove it ?

2023-02-04 02:52 UTC, Chr728 commented on Schema
> +);
@Ghaith-Chrit 

1. for first one you meant two different tweets for same hashtag , correct ? because you said same tweet that have same tweet , what do you mean ? . my understanding is we want to know how many is the hashtag count for each tweet, if two different tweets are using the same hashtag,with tweet id and hashtag id the count will be one depending if i put any of the tweet ids because both are the primary key. 
2. hashtage name is what comes after "#" , wanted as personal preference to limit by 15 , was not sure what is normally, and I thought normally its not longer than that. I can change the number if you have better suggestion , let me know. 
3. what people were saying in group is that frequency is the total number that this specific hashtag that is defined with hashtag id is used by general public  by many tweets. This is to know  this specific hashtag how often it is used, is it used a lot by everyone ?
4. if they will calculate the frequence considering the count per hour, per day, per week , the generated number should be stored as float or double, what you think ?

2023-02-04 02:53 UTC, Chr728 commented on Schema
> +TWEETERid SERIAL NOT NULL,
@Ghaith-Chrit since I cant have the same names, I wanted to change each time the same name slightly to not get any errors. If you want a covention to follow sure I can do it, names will be just longer.

2023-02-04 02:54 UTC, Chr728 commented on Schema
> +smodel_name VARCHAR(15) NOT NULL,
@Ghaith-Chrit knowing already our model names, I thought they wouldnt be longer than 15, how much do you want ?

2023-02-04 03:34 UTC, Ghaith-Chrit commented on Schema
> +lastname VARCHAR(30) NOT NULL
You can check the sample output in my PR. We can't fetch that info.

2023-02-04 03:35 UTC, Ghaith-Chrit commented on Schema
> +views_number int,
Unless there is a way to get that info, I say delete it. But let's wait for Tony. Maybe he knows something I don't.

2023-02-04 03:42 UTC, Ghaith-Chrit commented on Schema
> +);
1. Sorry, update the comment. We can get the count using the aggregate function `COUNT()` when executing the query, right?
2. Twitter does not impose that limit.
3. And why not just depend on the hashtag_count to get an idea often a hashtag is used?
4. Count per X? How will you get that info? The calculation will not be accurate since we are not getting all the tweets. I honestly do not see a use for this unless it helps with phase 2

2023-02-04 03:42 UTC, Ghaith-Chrit commented on Schema
> +TWEETERid SERIAL NOT NULL,
It is very confusing. Just stick to one way of naming the columns.

2023-02-04 03:44 UTC, Ghaith-Chrit commented on Schema
> +smodel_name VARCHAR(15) NOT NULL,
I mean if you prefer to have this limit, we can just use abbreviations.

2023-02-04 14:17 UTC, CHADBUCK13 requested changes

2023-02-04 14:17 UTC, CHADBUCK13 commented on Schema
> +twid SERIAL NOT NULL,
If you dont have to change the name of the foreign key, I would avoid it (i.e twid -> tid and userid -> uid). It makes it harder to cross reference the schema when its written with different attribute names.

2023-02-04 14:17 UTC, CHADBUCK13 commented on Schema
> +);
To add to Ghaith's first point, hashtags exist outside of tweets (i.e they don't have to be associated with any particular tweet). It is a many to many relationship captured by the contains relationship table.

I would also suggest making the primary key the name of the hashtag, because in twitter, hashtags are uniquely identified by the #<hashtag_name>

2023-02-04 14:17 UTC, CHADBUCK13 commented on Schema
> +);
I'm a little confused by the 'type' attribute. How do you determine the type? Is it not redundant since we are capturing the probability of the emotion being one of the types in the joy_prob, optimism_prob, etc attributes?

2023-02-04 14:17 UTC, CHADBUCK13 commented on Schema
> +CREATE TABLE "feels" (
It seems like we are mixing a many-to-many and one to many relationship here. In my opinion, each time we run the model on a tweet we should have a unique emotion captured in the database. Each emotion, therefore, should always be associated with one tweet. Thus, it can be captured simply by an attribute in the Emotion entity tweet_id, rather than a separate table.

2023-02-04 14:17 UTC, CHADBUCK13 commented on Schema
> +);
Same comments I left for emotions applies to sentiment (one-to-many relationship and type vs probability)

2023-02-07 02:15 UTC, janong24 approved these changes

2023-02-07 21:54 UTC, CHADBUCK13 requested changes

2023-02-07 21:54 UTC, CHADBUCK13 commented on Schema
> +sentiment_tweeter_id_Created SERIAL NOT NULL,
this doesnt really have anything to do with sentiment, also the name is too long

2023-02-07 21:54 UTC, CHADBUCK13 commented on Schema
> +sentiment_tweeter_id SERIAL NOT NULL,
same as above comment

2023-02-07 21:54 UTC, CHADBUCK13 commented on Schema
> +hashtag_name_contained varchar(255) NOT NULL,
just hashtag_name is fine (we dont have to have to type a bunch to make the queries)

2023-02-07 21:54 UTC, CHADBUCK13 commented on Schema
> +emotion_sentiment_tweeter_id SERIAL NOT NULL,
Again, just tid is fine here. Adding the rest is just longer and confusing

2023-02-07 21:54 UTC, CHADBUCK13 commented on Schema
> +sentiment_tweeter_id SERIAL NOT NULL,
same as above

2023-02-07 23:10 UTC, CHADBUCK13 approved these changes

2023-02-07 23:21 UTC, janong24 approved these changes

2023-02-08 13:23 UTC, Ghaith-Chrit approved these changes

2023-02-08 16:45 UTC, merged